=== Adamzynoni/mtf/Mtf/TestRunner/Rule/etc/rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Schema for DI configuration
 *
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                Root element of configuration.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rule" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="rule">
        <xs:annotation>
            <xs:documentation>
                Type of filtering rule. Type determined by attribute "scope"
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="filter" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="scope" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="testsuite"/>
                        <xs:enumeration value="testcase"/>
                        <xs:enumeration value="variation"/>
                        <xs:enumeration value="constraint"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="filter">
        <xs:annotation>
            <xs:documentation>
                Filter of rule.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="namespace"/>
                        <xs:enumeration value="module"/>
                        <xs:enumeration value="type"/>
                        <xs:enumeration value="module"/>
                        <xs:enumeration value="class"/>
                        <xs:enumeration value="tag"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="class" type="xs:string" use="required">
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Adamzynoni/mtf/Magento/Mtf/TestRunner/Rule/etc/rule.xml
<?xml version="1.0" ?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rule.xsd">
    <rule scope="testsuite">
        <filter name="namespace" class="Magento\Mtf\Util\Filter\TestSuiteNamespace" />
        <filter name="type" class="Magento\Mtf\Util\Filter\TestSuiteType"/>
        <filter name="module" class="Magento\Mtf\Util\Filter\TestSuiteModule"/>
        <filter name="class" class="Magento\Mtf\Util\Filter\TestSuiteClass"/>
    </rule>
    <rule scope="testcase">
        <filter name="tag" class="Magento\Mtf\Util\Filter\TestCaseTag"/>
    </rule>
    <rule scope="variation">
        <filter name="tag" class="Magento\Mtf\Util\Filter\VariationTag"/>
    </rule>
    <rule scope="constraint">
        <filter name="tag" class="Magento\Mtf\Util\Filter\ConstraintTag"/>
    </rule>
</config>
