=== Adamzynoni/mtf/Magento/Mtf/Fixture/etc/fixture.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Schema for fixtures
 *
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2015 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../../Repository/etc/repository.xsd" />
    <xs:element name="fixture">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="extends" minOccurs="0" maxOccurs="1" />
                <xs:element name="module" minOccurs="0" maxOccurs="1" />
                <xs:element name="type" minOccurs="0" maxOccurs="1" />
                <xs:element name="entity_type" minOccurs="0" maxOccurs="1" />
                <xs:element name="product_type" minOccurs="0" maxOccurs="1" />
                <xs:element name="collection" minOccurs="0" maxOccurs="1" />
                <xs:element name="identifier" minOccurs="0" maxOccurs="1" />
                <xs:element name="repository_class" minOccurs="0" maxOccurs="1" />
                <xs:element name="handler_interface" minOccurs="0" maxOccurs="1" />
                <xs:element name="dataset" type="datasetType" minOccurs="0" maxOccurs="1" />
                <xs:element name="data_config" type="dataConfigType" minOccurs="0" maxOccurs="1" />
                <xs:element name="fields" type="fieldsType" minOccurs="1" maxOccurs="1" />
                <xs:element name="entities" type="entitiesType" minOccurs="0" maxOccurs="1" />
            </xs:choice>
            <xs:attribute name="class" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="fieldType">
        <xs:annotation>
            <xs:documentation>
                With field node you are able to bewrite field properties in fixture.
            </xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded">
            <xs:element name="attribute_code" minOccurs="1" maxOccurs="1" type="xs:string" />
            <xs:element name="is_required" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="backend_type" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="default_value" minOccurs="0" maxOccurs="1" type="xs:all" />
            <xs:element name="input" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="group" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="source" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="frontend_input" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="frontend_label" minOccurs="0" maxOccurs="1" type="xs:string" />
        </xs:choice>
        <xs:attribute name="name" use="required" />
    </xs:complexType>

    <xs:complexType name="fieldsType">
        <xs:annotation>
            <xs:documentation>
                Fields is a root node for fields in your fixture.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="field" type="fieldType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="fieldName">
                    <xs:selector xpath="field" />
                    <xs:field xpath="@name" />
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="entitiesType">
        <xs:annotation>
            <xs:documentation>
                Entities is a root node for entity in your fixture.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="entity" type="entityType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="entityName">
                    <xs:selector xpath="entity" />
                    <xs:field xpath="@name" />
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="entityType">
        <xs:annotation>
            <xs:documentation>
                With field node you are able to bewrite field properties in fixture.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" use="required" />
    </xs:complexType>

    <xs:complexType name="dataConfigType">
        <xs:annotation>
            <xs:documentation>
                Data config is a root node for configuration in your fixture.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="item" type="argumentType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="itemName">
                    <xs:selector xpath="item" />
                    <xs:field xpath="@name" />
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Adamzynoni/mtf/tests/app/Magento/Mtf/Test/Fixture/Test.xml
<?xml version="1.0" ?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

-->
<fixture class="Magento\Mtf\Test\Fixture\Test"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../../../Mtf/Fixture/etc/fixture.xsd">
    <module>Magento_Mtf</module>
    <type>blank</type>
    <entity_type>test_fixture</entity_type>
    <fields>
        <field name="locator">
            <attribute_code>locator</attribute_code>
            <frontend_input>text</frontend_input>
            <frontend_label>Locator</frontend_label>
            <is_required>1</is_required>
            <default_value xsi:type="string">About</default_value>
        </field>
        <field name="strategy">
            <attribute_code>strategy</attribute_code>
            <frontend_input>text</frontend_input>
            <frontend_label>Strategy</frontend_label>
            <is_required>1</is_required>
            <default_value xsi:type="string">link text</default_value>
            <source>Magento\Mtf\Test\Fixture\Test\Strategy</source>
        </field>
        <field name="search">
            <attribute_code>search</attribute_code>
        </field>
        <field name="type">
            <attribute_code>type</attribute_code>
        </field>
    </fields>
    <repository_class>Magento\Mtf\Test\Repository\Test</repository_class>
    <handler_interface>Magento\Mtf\Test\Handler\Test\TestInterface</handler_interface>
</fixture>

=== Adamzynoni/mtf/tests/app/Magento/Mtf/Test/Fixture/BlockRenderMtf.xml
<?xml version="1.0" ?>
<!--
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @copyright   Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
-->
<fixture class="Magento\Mtf\Test\Fixture\BlockRenderMtf"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../../../../Mtf/Fixture/etc/fixture.xsd">
    <extends>\Magento\BlockRender\Test\Fixture\BlockRender</extends>
    <fields>
        <field name="strategy">
            <attribute_code>strategy</attribute_code>
            <frontend_input>text</frontend_input>
            <frontend_label>Strategy</frontend_label>
            <is_required>1</is_required>
            <default_value xsi:type="string">link text</default_value>
            <source>Magento\Mtf\BlockRender\Fixture\Test\Strategy</source>
        </field>
        <field name="type">
            <attribute_code>type</attribute_code>
        </field>
    </fields>
</fixture>
